# Generated by Django 2.1.5 on 2019-02-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='tokenqr',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Añadida A Un Usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ci',
            field=models.CharField(max_length=8, unique=True, verbose_name='Cedula'),
        ),
    ]
